version: "3"
services:
  workspace_python:
    container_name: "workspace_python"
    build: 
      context: .
      args:
        VARIANT: 3
        INSTALL_NODE: "false"
        NODE_VERSION: lts/*
    environment:
      - PYTHONPATH=/workspaces/python
    volumes:
      - ../:/workspaces/python
    command: sleep infinity

  selenium-hub:
    image: selenium/hub:4
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    
  chrome_1:
    image: selenium/node-chrome:4
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
    ports:
      - "6900:5900"
    
  chrome_2:
    image: selenium/node-chrome:4
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
    ports:
      - "6901:5900"